name: Run Bot (Self-triggering)

on:
  workflow_dispatch: # Allows manual start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      # === SETUP CHROME PROFILE ===
      - name: Setup Chrome Profile
        run: |
          # Download profile from your GitHub repo - CORRECT URL
          wget -q https://github.com/teejeedeeone2025/studious-winner/raw/main/my_google_profile.tar.gz
          
          # Check if download was successful
          if [ ! -f "my_google_profile.tar.gz" ]; then
              echo "❌ Download failed! File not found."
              echo "Please check the URL: https://github.com/teejeedeeone2025/studious-winner/raw/main/my_google_profile.tar.gz"
              exit 1
          fi
          
          # Create directory and extract with correct structure
          mkdir -p my_google_profile
          tar -xzf my_google_profile.tar.gz -C my_google_profile
          
          # Verify the extracted structure
          echo "🔍 Checking profile contents..."
          
          if [ ! -d "my_google_profile/google-chrome" ]; then
              echo "❌ Extraction failed! Profile structure incorrect."
              echo "Contents of downloaded archive:"
              tar -tzf my_google_profile.tar.gz | head -10
              exit 1
          fi
          
          # Check for Google Profile Picture
          if [ -f "my_google_profile/google-chrome/Default/Google Profile Picture.png" ]; then
              echo "✅ Google Profile Picture found - real user profile"
          else
              echo "❌ Google Profile Picture missing"
              echo "Files in Default directory:"
              ls -la my_google_profile/google-chrome/Default/ | head -10
          fi
          
          # Check for Cookies file
          if [ -f "my_google_profile/google-chrome/Default/Cookies" ]; then
              echo "✅ Cookies file found"
          else
              echo "❌ Cookies file missing"
          fi
          
          # Clean up
          rm my_google_profile.tar.gz

      # === INSTALL CHROME ===
      - name: Install Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y
          rm google-chrome-stable_current_amd64.deb
          echo "Chrome version:"
          google-chrome --version

      # === RUN BOT ===
      - name: Run bot
        run: python bot.py

      # === SELF-TRIGGERING ===
      - name: Delay before next run
        run: sleep 300

      - name: Trigger Next Run
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches" \
          -d '{"ref":"main"}'
