name: Run Bot (Self-triggering)

on:
  workflow_dispatch: # Allows manual start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (this gets your bot.py, requirements.txt, AND your profile)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- NEW STEP: SETUP CHROME PROFILE ---
      - name: Setup Chrome Profile
        run: |
          mkdir -p ~/.config/google-chrome/Default
          # Download the profile from YOUR repository
          wget -q https://github.com/teejeedeeone2025/studious-winner/raw/main/my_google_profile.tar.gz
          # Extract it to the Chrome config directory
          tar -xzf my_google_profile.tar.gz -C ~/.config/google-chrome/Default/ --strip-components=5
          echo "✅ Chrome profile injected"

      # --- NEW STEP: INSTALL CHROME ---
      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4: Run bot (Now with Chrome installed and profile loaded)
      - name: Run bot
        run: python bot.py

      # Add delay before next trigger (5 minutes = 300 seconds)
      - name: Delay before next run
        run: sleep 500

      # Self-trigger next run
      - name: Trigger Next Run
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches" \
          -d '{"ref":"main"}'
