name: Run Bot (Self-triggering)

on:
  workflow_dispatch: # Allows manual start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      # === SETUP CHROME PROFILE ===
      - name: Setup Chrome Profile
        run: |
          # Download profile from your GitHub repo
          wget -q https://github.com/teejeedeeone2025/studious-winner/raw/main/my_google_profile.tar.gz
          
          # Create directory and extract with correct structure
          mkdir -p my_google_profile
          tar -xzf my_google_profile.tar.gz -C my_google_profile
          
          # Verify the extracted structure
          echo "📦 Extracted profile contents:"
          find my_google_profile -type f | head -10
          
          # Check if cookies exist (critical for login)
          if [ -f "my_google_profile/google-chrome/Default/Cookies" ]; then
              echo "✅ Cookies file found - profile should work"
          else
              echo "❌ Cookies file missing - profile won't work"
              echo "Files in Default directory:"
              ls -la my_google_profile/google-chrome/Default/ || true
          fi
          
          # Clean up
          rm my_google_profile.tar.gz

      # === INSTALL CHROME ===
      - name: Install Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y
          rm google-chrome-stable_current_amd64.deb
          echo "Chrome version:"
          google-chrome --version

      # === RUN BOT ===
      - name: Run bot
        run: python bot.py

      # === SELF-TRIGGERING ===
      - name: Delay before next run
        run: sleep 300

      - name: Trigger Next Run
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches" \
          -d '{"ref":"main"}'
